language: python
python:
  - 3.7

install:
  - pip install -q -r requirements_c_flake8.txt codecov
script:
  - flake8
  - pytest libpythonpro
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov

